// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJmg36vwgZSsgp9nftHUEApUFsKIScKhI',
    appId: '1:370318450299:web:e6f423a5af658d5d1dccde',
    messagingSenderId: '370318450299',
    projectId: 'testdrive-2b4d8',
    authDomain: 'testdrive-2b4d8.firebaseapp.com',
    storageBucket: 'testdrive-2b4d8.appspot.com',
    measurementId: 'G-2SJM3HWNGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa-nC21S15BLxCS2RZnYyiNslw-AOiLIk',
    appId: '1:370318450299:android:caff49526c27a6e31dccde',
    messagingSenderId: '370318450299',
    projectId: 'testdrive-2b4d8',
    storageBucket: 'testdrive-2b4d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD17eSgxLVmWVYsTIwzzcWncj40MI-Br8o',
    appId: '1:370318450299:ios:57429426d8f59eb01dccde',
    messagingSenderId: '370318450299',
    projectId: 'testdrive-2b4d8',
    storageBucket: 'testdrive-2b4d8.appspot.com',
    iosBundleId: 'com.example.testDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD17eSgxLVmWVYsTIwzzcWncj40MI-Br8o',
    appId: '1:370318450299:ios:57429426d8f59eb01dccde',
    messagingSenderId: '370318450299',
    projectId: 'testdrive-2b4d8',
    storageBucket: 'testdrive-2b4d8.appspot.com',
    iosBundleId: 'com.example.testDrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJmg36vwgZSsgp9nftHUEApUFsKIScKhI',
    appId: '1:370318450299:web:d5ca6c1bcdbfb4891dccde',
    messagingSenderId: '370318450299',
    projectId: 'testdrive-2b4d8',
    authDomain: 'testdrive-2b4d8.firebaseapp.com',
    storageBucket: 'testdrive-2b4d8.appspot.com',
    measurementId: 'G-EWH2Z7B2F8',
  );
}
